# Generated by Django 6.0.2 on 2026-03-27 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Benim Sitem', max_length=150, verbose_name='Site adı')),
                ('site_slogan', models.CharField(blank=True, max_length=250, null=True, verbose_name='Slogan')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Site Açıklaması')),
                ('keywords', models.CharField(blank=True, max_length=250, null=True, verbose_name='Anahtar Kelimeler')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/favicon/')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon')),
                ('phone2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon-2')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('email2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta-2')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='YouTube')),
                ('google_map_iframe', models.TextField(blank=True, null=True, verbose_name='Google Maps Embed Kodu')),
            ],
            options={
                'verbose_name': 'Site Ayarı',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Reklam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('banner', 'Banner Reklam'), ('resim1', 'Reklam Resmi 1'), ('resim2', 'Reklam Resmi 2'), ('resim3', 'Reklam Resmi 3')], default='banner', max_length=50, verbose_name='Reklam Yeri')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='Reklam Görseli')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Reklam Linki')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reklamlar', to='site_ayarları.sitesettings')),
            ],
        ),
    ]
