# Generated by Django 6.0.2 on 2026-03-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_ayarları', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reklam',
            name='position',
            field=models.CharField(choices=[('Seciniz', ' Reklam Yeri Seçiniz'), ('banner', 'Banner Reklam'), ('resim1', 'Reklam Resmi 1'), ('resim2', 'Reklam Resmi 2'), ('resim3', 'Reklam Resmi 3')], default='Seciniz', max_length=50, verbose_name='Reklam Yeri'),
        ),
    ]
