# Generated by Django 6.0.2 on 2026-03-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_ayarları', '0002_alter_reklam_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_adsense_client_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Google AdSense Client ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Google Analytics ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_search_console_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Google Search Console Doğrulama Kodu'),
        ),
        migrations.AlterField(
            model_name='reklam',
            name='position',
            field=models.CharField(choices=[('Seciniz', ' Reklam Alanı Seçiniz'), ('banner', 'Banner Reklam'), ('resim1', 'Reklam Resmi 1'), ('resim2', 'Reklam Resmi 2'), ('resim3', 'Reklam Resmi 3')], default='Seciniz', max_length=50, verbose_name='Reklam Yeri'),
        ),
    ]
