# Generated by Django 6.0.2 on 2026-03-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_ayarları', '0003_sitesettings_google_adsense_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reklam',
            name='position',
            field=models.CharField(choices=[('Seciniz', ' Reklam Alanı Seçiniz'), ('banner', 'Banner Reklam'), ('haber_detay', 'Haber Detay Sayfası'), ('resim2', 'Reklam Resmi 2'), ('resim3', 'Reklam Resmi 3')], default='Seciniz', max_length=50, verbose_name='Reklam Yeri'),
        ),
    ]
