# Generated by Django 6.0.2 on 2026-03-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_ayarları', '0004_alter_reklam_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reklam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='Reklam Görselleri'),
        ),
        migrations.AlterField(
            model_name='reklam',
            name='url',
            field=models.URLField(blank=True, default='#', help_text='Reklama tıklandığında gidilecek URL', null=True, verbose_name='Reklam Linki'),
        ),
    ]
