# Generated by Django 6.0.2 on 2026-03-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_ayarları', '0005_alter_reklam_image_alter_reklam_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reklam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Reklamlar/', verbose_name='Reklam Görseli'),
        ),
        migrations.AlterField(
            model_name='reklam',
            name='url',
            field=models.URLField(help_text='Reklama tıklandığında gidilecek URL', verbose_name='Reklam Linki'),
        ),
    ]
