# Generated by Django 6.0.2 on 2026-03-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_ayarları', '0006_alter_reklam_image_alter_reklam_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reklam',
            name='url',
            field=models.URLField(blank=True, help_text='Reklama tıklandığında gidilecek URL', null=True, verbose_name='Reklam Linki'),
        ),
    ]
