# Generated by Django 6.0.2 on 2026-03-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_ayarları', '0007_alter_reklam_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reklam',
            name='position',
            field=models.CharField(choices=[('Seciniz', ' Reklam Alanı Seçiniz'), ('banner', 'Banner Reklam'), ('haber_detay', 'Haber Detay Sayfası'), ('yazar_detay', 'Yazar Detay Sayfası')], default='Seciniz', max_length=50, verbose_name='Reklam Yeri'),
        ),
    ]
