# Generated by Django 6.0.2 on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_ayarları", "0008_alter_reklam_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="RSSFeedSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=120, verbose_name="Baslik")),
                ("feed_url", models.URLField(unique=True, verbose_name="RSS Feed URL")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Sira")),
                ("item_limit", models.PositiveSmallIntegerField(default=5, verbose_name="Kayit Limiti")),
            ],
            options={
                "verbose_name": "Icerik Bolumu (RSS)",
                "verbose_name_plural": "Icerik Bolumleri (RSS)",
                "ordering": ["order", "id"],
            },
        ),
    ]
