# Generated by Django 6.0.2 on 2026-03-31 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site_ayarları", "0009_rssfeedsource"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reklam",
            old_name="name",
            new_name="site_settings",
        ),
    ]
