# Generated by Django 6.0.2 on 2026-03-31 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site_ayarları", "0010_rename_reklam_name_site_settings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reklam",
            old_name="site_settings",
            new_name="name",
        ),
    ]
