# Generated by Django 6.0.2 on 2026-04-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_ayarları', '0012_sitesettings_rss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook',
            field=models.URLField(default='#', verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram',
            field=models.URLField(default='#', verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='linkedin',
            field=models.URLField(default='#', verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='rss',
            field=models.URLField(default='#', verbose_name='RSS'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='twitter',
            field=models.URLField(default='#', verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube',
            field=models.URLField(default='#', verbose_name='YouTube'),
        ),
    ]
