# Generated by Django 6.0.2 on 2026-04-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_ayarları', '0014_sitesettings_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='rss',
            field=models.URLField(blank=True, null=True, verbose_name='RSS'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube'),
        ),
    ]
