# Generated by Django 6.0.2 on 2026-02-08 19:42

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='başlık')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('content', tinymce.models.HTMLField(verbose_name='içerik')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='yayımlanma tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='haber_resimleri/', verbose_name='resim')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.news')),
            ],
        ),
    ]
