# Generated by Django 6.0.2 on 2026-02-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsimage',
            options={'verbose_name': 'Haber ', 'verbose_name_plural': 'Haberler'},
        ),
    ]
