# Generated by Django 6.0.2 on 2026-02-09 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_newsimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Haber ', 'verbose_name_plural': 'Haberler'},
        ),
        migrations.AlterModelOptions(
            name='newsimage',
            options={},
        ),
    ]
