# Generated by Django 6.0.2 on 2026-02-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_news_options_alter_newsimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_date'], 'verbose_name': 'Haber ', 'verbose_name_plural': 'Haberler'},
        ),
        migrations.AlterModelOptions(
            name='newsimage',
            options={'verbose_name': 'Haber Resmi', 'verbose_name_plural': 'Haber Resimleri'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='name',
        ),
    ]
