# Generated by Django 6.0.2 on 2026-02-21 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_newsvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='newsimage',
            options={'ordering': ['order'], 'verbose_name': 'Haber Resmi', 'verbose_name_plural': 'Haber Resimleri'},
        ),
        migrations.AlterModelOptions(
            name='newsvideo',
            options={'ordering': ['order'], 'verbose_name': 'Haber Videosu', 'verbose_name_plural': 'Haber Videoları'},
        ),
        migrations.RemoveField(
            model_name='newsvideo',
            name='video',
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='pages.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newsimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsvideo',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='newsvideo',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='news_videos/'),
        ),
        migrations.AddField(
            model_name='newsvideo',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='pages.author'),
            preserve_default=False,
        ),
    ]
