# Generated by Django 6.0.2 on 2026-02-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_author_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Yazar', 'verbose_name_plural': 'Yazarlar'},
        ),
    ]
