# Generated by Django 6.0.2 on 2026-02-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_author_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Haber Yayında'),
        ),
    ]
