# Generated by Django 6.0.2 on 2026-02-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_news_order_alter_news_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['order', '-published_date'], 'verbose_name': 'Haber ', 'verbose_name_plural': 'Haberler'},
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='görsel sırası'),
        ),
    ]
