# Generated by Django 6.0.2 on 2026-02-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_news_options_alter_newsimage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Haber Sırası'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
