# Generated by Django 6.0.2 on 2026-02-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsvideo',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
