# Generated by Django 6.0.2 on 2026-03-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_newsvideo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsvideo',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='video adı'),
        ),
    ]
