# Generated by Django 6.0.2 on 2026-03-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_author_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='author',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='author',
            name='pinterest_url',
            field=models.URLField(blank=True, null=True, verbose_name='Pinterest URL'),
        ),
        migrations.AddField(
            model_name='author',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter URL'),
        ),
    ]
