# Generated by Django 6.0.2 on 2026-03-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_author_facebook_url_author_linkedin_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='pinterest_url',
        ),
        migrations.AddField(
            model_name='author',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='İnstagram URL'),
        ),
    ]
