"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import environ
import os
from pathlib import Path


# Initialize environment variables


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

SECRET_KEY = env('SECRET_KEY')
DEBUG = env.bool('DEBUG', default=True)
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/









# Application definition

INSTALLED_APPS = [
    # "pages.apps.PagesConfig",  # haber resimleri silen sinyaller
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # kendi uygulamalarımız (apps)
    "pages",
    "site_ayarları",

    # üçüncü taraf uygulamalar (third-party apps)
    'django.contrib.sitemaps', # Sitemap için ekledik
    "django_cleanup.apps.CleanupConfig",  # haber resimleri silinirken dosyaların da silinmesi için
    "tinymce",
    "easy_thumbnails",
    "adminsortable2",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "site_ayarları.context.menu",  # Her template'de `menus` değişkenini kullanılabilir hale getirir
                "site_ayarları.context.site_settings",  # Her template'de `site_settings` değişkenini kullanılabilir hale getirir
                "site_ayarları.context.site_structured_data",  # Her template'de `site_structured_data` değişkenini kullanılabilir hale getirir
                "site_ayarları.context.site_categories",  # Her template'de `site_categories` değişkenini kullanılabilir hale getirir
                "site_ayarları.context.hava_durumu",  # Header icin hava durumu verisi
                "site_ayarları.context.tcmb_piyasa_verileri",  # Header ticker icin TCMB piyasa verileri
                "site_ayarları.context.borsa_hisse_verileri",  # Borsa hisse senetleri verisi
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASE_URL = env.str("DATABASE_URL", default="").strip()

if DATABASE_URL:
    DATABASES = {
        "default": env.db("DATABASE_URL"),
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": env.str("DB_ENGINE", default="django.db.backends.mysql"),
            "NAME": env.str("DB_NAME", default="django6"),
            "USER": env.str("DB_USER", default="add"),
            "PASSWORD": env.str("DB_PASSWORD", default="123456"),
            "HOST": env.str("DB_HOST", default="localhost"),
            "PORT": env.str("DB_PORT", default="3306"),
            "OPTIONS": {
                "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
                "charset": "utf8mb3",
            },
        },
    }

# MySQL kullaniliyorsa Strict Mode'u her baglanti yolunda zorunlu tut.
if DATABASES["default"].get("ENGINE") == "django.db.backends.mysql":
    db_options = DATABASES["default"].setdefault("OPTIONS", {})
    db_options.setdefault("init_command", "SET sql_mode='STRICT_TRANS_TABLES'")
    db_options.setdefault("charset", "utf8mb3")

'''
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "django6",
        "USER": "add",
        "PASSWORD": "123456",
        "HOST": "localhost",
        "PORT": "3306",
        "OPTIONS": {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            "charset": "utf8mb3",
        },
    }
}
'''


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "tr-TR"

TIME_ZONE = "Europe/Istanbul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
#STATIC_ROOT = BASE_DIR / "staticfiles"# collectstatic komutu ile tüm statik dosyaların kopyalanacağı dizin yayına çıkarken
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


TINYMCE_DEFAULT_CONFIG = {
    "height": 360,
}


# Easy Thumbnails Configuration
THUMBNAIL_ALIASES = {
    "": {
        "slider": {"size": (690, 418), "crop": "center"},
        "category": {"size": (310, 206), "crop": "center"},
        "yazar": {"size": (300, 192), "crop": "center"},
        "video": {"size": (310, 175), "crop": "center"},
        "haber_sayfa_reklam": {"size": (341, 346), "crop": "center"},
        "ust_banner_reklam": {"size": (750, 90), "crop": "center"},
    },
}

THUMBNAIL_PROCESSORS = (
    "easy_thumbnails.processors.colorspace",
    "easy_thumbnails.processors.autocrop",
    "easy_thumbnails.processors.scale_and_crop",
    "easy_thumbnails.processors.filters",
)

THUMBNAIL_HIGH_RESOLUTION = True
THUMBNAIL_PRESERVE_FORMAT = True

# WebP'ye dönüştürülmesini istemediğimiz formatlar (örn. PNG, GIF) için uzantıları belirtin
THUMBNAIL_PRESERVE_EXTENSIONS = "gif"  # Bunlar hariç her şeyi dönüştür
THUMBNAIL_SUBDIR = "thumbs"
THUMBNAIL_FORMAT = "WEBP"  # Çıktı formatı WebP
THUMBNAIL_QUALITY = 85

# Cache Ayarı (Redis veya Database tabanlı olabilir)
if DEBUG:
    # Geliştirme aşamasında Redis'e ihtiyaç duymaz, hata vermez
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.dummy.DummyCache",
        }
    }
else:
    # Canlıya (Production) geçtiğinde Redis aktif olur
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": env('REDIS_URL'),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            }
        }
    }
CACHE_TTL = 60 * 60 * 6
